config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show
  
  get 'introduction/:id', to: 'users#intro', as: :introduction
  patch 'users/:id', to: 'users#update'

  resources :pins do
    member do
      put "like", to: "pins#like"
    end
  end
  root "pins#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :user
  acts_as_votable
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :pins, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :like ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @pins = Pin.all.order("created_at DESC").includes(:user)
  end

  def show
  end

  def edit
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "更新成功！"
    else
      render 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to root_path, notice: "刪除成功"
  end

  def new
    @pin = current_user.pins.build
  end
  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: "發文成功！"
    else
      render 'new'
    end
  end

  def like
    @pin.liked_by(current_user)
    redirect_to :back
  end

  private
    def pin_params
      params.require(:pin).permit(:title, :description, :image)
    end
    def find_pin
      @pin = Pin.find(params[:id])
    end
    def correct_user
      redirect_to root_path, notice: "你沒有權限!" unless @pin.user == current_user
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :intro
  before_action :correct_user, only: :intro
  before_action :find_user, only: [:show, :update, :intro, :update]
  def show
  end
  def intro
  end
  def update
    if @user.update(params_user)
      redirect_to @user, notice: "修改成功！"
    else
      render 'intro'
    end
  end
  private
    def correct_user
      @user = User.find(params[:id])
      redirect_to root_url, notice: "你沒有權限!" unless @user == current_user
    end

    def params_user
      params.require(:user).permit(:introduction)
    end

    def find_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    類似Pinterest的網站
  %nav.nav
    %ul.nav.navbar-nav.navbar-right
      %li= link_to "關於", "#"
      %li= link_to "聯絡", "#"

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-brand= link_to "PinterestApp", root_path
    - if user_signed_in?
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "新Pin", new_pin_path
        %li= link_to "帳戶", edit_user_registration_path
        %li= link_to "登出", destroy_user_session_path, method: :delete
    - else
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "註冊", new_user_registration_path
        %li= link_to "登入", new_user_session_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title PinterestApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/header'
    .container
      - flash.each do |name, msg|
        = content_tag :div, msg, class: "alert alert-info"
      = yield

app/views/pins/_form.html.haml
= simple_form_for @pin do |f|
  - if @pin.errors.any?
    %h2
      = @pin.errors.count
    %ul
      - @pin.errors.full_messages.each do |msg|
        %li= msg
  .form_group
    = f.input :title, label: "標題", input_html: { class: "form-control"}
  .form_group
    = f.input :description, label: "描述", input_html: { class: "form-control"}
  .form_group
    = f.input :image, label: "上傳圖片", input_html: { class: "form-control"}

  = f.button :submit, yield(:btn_text), class: "btn btn-primary"

app/views/pins/edit.html.haml
- provide(:btn_text, "更新")
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 編輯
      .panel-body
        = image_tag @pin.image.url(:medium)
        = render 'form'

app/views/pins/index.html.haml
#pins.transitions-enabled
  - @pins.each do |pin|
    .box.panel.panel-default
      = link_to (image_tag pin.image.url), pin
      .panel-body
        %h2= link_to pin.title, pin
        %p.user
        擁有者
        = pin.user.email

app/views/pins/new.html.haml
- provide(:btn_text, "建立")
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 新增
      .panel-body
        = render 'form'

app/views/pins/show.html.haml
#pin_show.row
  .col-md-8.col-md-offset-2
    .panel.panel-deafult
      .panel-heading.pin_image
        = image_tag @pin.image
      .panel-body
        %h1= @pin.title
        %p= @pin.description
        %p
          此篇文章由
          = link_to @pin.user.email, user_path(@pin.user)
          寫
      .panel-footer
        .row
          .col-md-6
            %p.user
              此篇文章由
              = @pin.user.email
              寫
          .col-md-6
            .btn-group.pull-right
              = link_to like_pin_path, method: :put, class: "btn btn-default" do
                %span.glyphicon.glyphicon-heart
                  = @pin.get_likes.size
              - if user_signed_in? && @pin.user == current_user
                = link_to "修改", edit_pin_path(@pin), class: "btn btn-default"
                = link_to "刪除", pin_path, method: :delete, data: { confirm: "確定刪除?" }, class: "btn btn-default"

app/views/users/intro.html.haml
= simple_form_for @user do |f|
  - if @user.errors.any?
    %h2
      = @user.errors.count
    %ul
      - @user.errors.full_messages.each do |msg|
        %li= msg
  .form_group
    = f.input :introduction, label: "介紹", input_html: { class: "form-control"}

  = f.button :submit, "修改", class: "btn btn-primary"

app/views/users/show.html.haml
.col-md-8.col-md-offset-2
  .panel.panel-default
    .panel-heading
      %h1
        = @user.email
        的介紹
    .panel-body
      %p= @user.introduction
      - if user_signed_in? && @user == current_user
        =link_to '編輯介紹', introduction_path